[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "18"

[build]
  command = "OUTPUT=netlify astro build"
  publish = "dist"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[redirects]]
  from = "https://chatgpt.99app.cn/"
  to = "https://gpt.99app.cn/:splat"
  status = 301
  force = true
